from suep_toolkit.auth.service import AuthService, AuthServiceError
